"""News sentiment signal generator."""

from contextlib import suppress
from datetime import date, timedelta

import duckdb

from equity_lake.core.paths import US_NEWS_DIR
from equity_lake.domain.signals.generators.base import SignalGenerator
from equity_lake.domain.signals.models import Signal


class SentimentSignalGenerator(SignalGenerator):
    """Generate signals based on news sentiment analysis.

    Reuses locally stored news sentiment data generated by the ingestion
    pipeline. Generates BUY when sentiment is positive, SELL when negative.
    """

    def __init__(self, config: dict):
        super().__init__(config)
        self.buy_threshold = config.get("buy_threshold", 0.5)
        self.sell_threshold = config.get("sell_threshold", -0.3)
        self.min_articles = config.get("min_articles", 3)
        self.lookback_days = config.get("lookback_days", 7)
        self.con = duckdb.connect(":memory:")
        self._setup_view()

    def _setup_view(self) -> None:
        """Create DuckDB view for locally stored news sentiment data."""
        news_pattern = f"{US_NEWS_DIR}/date=*/*.parquet"
        sql = f"""
        CREATE OR REPLACE VIEW news_data AS
        SELECT * FROM read_parquet('{news_pattern}', hive_partitioning=1)
        """
        with suppress(Exception):
            self.con.execute(sql)

    def _load_sentiment_summary(self, ticker: str, start_date: date, target_date: date) -> dict | None:
        """Load aggregated sentiment for a ticker from local news history."""
        query = f"""
        SELECT
            AVG(sentiment_score) AS avg_sentiment,
            COUNT(*) AS article_count
        FROM news_data
        WHERE ticker = '{ticker}'
          AND date >= '{start_date}'
          AND date <= '{target_date}'
        """

        try:
            row = self.con.execute(query).fetchone()
        except Exception:
            return None

        if row is None:
            return None

        avg_sentiment, article_count = row
        if article_count == 0:
            return None

        return {
            "avg_sentiment": float(avg_sentiment or 0.0),
            "article_count": int(article_count),
        }

    def generate(self, ticker: str, target_date: date) -> Signal | None:
        """Generate signal based on news sentiment.

        Args:
            ticker: Stock symbol
            target_date: Date to generate signal for

        Returns:
            Signal with action based on sentiment score
        """
        if not self.is_enabled():
            return None

        # Calculate date range for news lookup
        start_date = target_date - timedelta(days=self.lookback_days)

        sentiment_data = self._load_sentiment_summary(ticker, start_date, target_date)
        if not sentiment_data:
            return None

        # Extract sentiment score and article count
        avg_sentiment = sentiment_data.get("avg_sentiment", 0)
        article_count = sentiment_data.get("article_count", 0)

        # Check minimum article threshold
        if article_count < self.min_articles:
            return None

        # Generate signal based on sentiment
        if avg_sentiment >= self.buy_threshold:
            return Signal(
                ticker=ticker,
                date=target_date,
                signal_type="sentiment",
                action="BUY",
                confidence=65.0,
                reasoning=f"Positive sentiment: {avg_sentiment:.2f} from {article_count} articles",
                metadata={
                    "sentiment_score": avg_sentiment,
                    "article_count": article_count,
                    "lookback_days": self.lookback_days,
                },
            )
        elif avg_sentiment <= self.sell_threshold:
            return Signal(
                ticker=ticker,
                date=target_date,
                signal_type="sentiment",
                action="SELL",
                confidence=60.0,
                reasoning=f"Negative sentiment: {avg_sentiment:.2f} from {article_count} articles",
                metadata={
                    "sentiment_score": avg_sentiment,
                    "article_count": article_count,
                    "lookback_days": self.lookback_days,
                },
            )

        return None
